# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from biostarPython.service import cert_pb2 as cert__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in cert_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CertStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateServerCertificate = channel.unary_unary(
                '/gsdk.cert.Cert/CreateServerCertificate',
                request_serializer=cert__pb2.CreateServerCertificateRequest.SerializeToString,
                response_deserializer=cert__pb2.CreateServerCertificateResponse.FromString,
                _registered_method=True)
        self.SetServerCertificate = channel.unary_unary(
                '/gsdk.cert.Cert/SetServerCertificate',
                request_serializer=cert__pb2.SetServerCertificateRequest.SerializeToString,
                response_deserializer=cert__pb2.SetServerCertificateResponse.FromString,
                _registered_method=True)
        self.SetGatewayCertificate = channel.unary_unary(
                '/gsdk.cert.Cert/SetGatewayCertificate',
                request_serializer=cert__pb2.SetGatewayCertificateRequest.SerializeToString,
                response_deserializer=cert__pb2.SetGatewayCertificateResponse.FromString,
                _registered_method=True)


class CertServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateServerCertificate(self, request, context):
        """Server Certificate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetServerCertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGatewayCertificate(self, request, context):
        """Set Gatweay Certificate: for Device Gateway only
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CertServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateServerCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateServerCertificate,
                    request_deserializer=cert__pb2.CreateServerCertificateRequest.FromString,
                    response_serializer=cert__pb2.CreateServerCertificateResponse.SerializeToString,
            ),
            'SetServerCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetServerCertificate,
                    request_deserializer=cert__pb2.SetServerCertificateRequest.FromString,
                    response_serializer=cert__pb2.SetServerCertificateResponse.SerializeToString,
            ),
            'SetGatewayCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGatewayCertificate,
                    request_deserializer=cert__pb2.SetGatewayCertificateRequest.FromString,
                    response_serializer=cert__pb2.SetGatewayCertificateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gsdk.cert.Cert', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gsdk.cert.Cert', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Cert(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateServerCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gsdk.cert.Cert/CreateServerCertificate',
            cert__pb2.CreateServerCertificateRequest.SerializeToString,
            cert__pb2.CreateServerCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetServerCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gsdk.cert.Cert/SetServerCertificate',
            cert__pb2.SetServerCertificateRequest.SerializeToString,
            cert__pb2.SetServerCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGatewayCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gsdk.cert.Cert/SetGatewayCertificate',
            cert__pb2.SetGatewayCertificateRequest.SerializeToString,
            cert__pb2.SetGatewayCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
