# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65rror.proto\x12\x05\x65rror\"<\n\rErrorResponse\x12\x10\n\x08\x64\x65viceID\x18\x01 \x01(\r\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t2\x07\n\x05\x45rrorB3\n\x18\x63om.supremainc.sdk.errorP\x01Z\x15\x62iostar/service/errorb\x06proto3')



_ERRORRESPONSE = DESCRIPTOR.message_types_by_name['ErrorResponse']
ErrorResponse = _reflection.GeneratedProtocolMessageType('ErrorResponse', (_message.Message,), {
  'DESCRIPTOR' : _ERRORRESPONSE,
  '__module__' : 'error_pb2'
  # @@protoc_insertion_point(class_scope:error.ErrorResponse)
  })
_sym_db.RegisterMessage(ErrorResponse)

_ERROR = DESCRIPTOR.services_by_name['Error']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.supremainc.sdk.errorP\001Z\025biostar/service/error'
  _ERRORRESPONSE._serialized_start=22
  _ERRORRESPONSE._serialized_end=82
  _ERROR._serialized_start=84
  _ERROR._serialized_end=91
# @@protoc_insertion_point(module_scope)
