# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: masteradmin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'masteradmin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from biostarPython.service import user_pb2 as user__pb2
from biostarPython.service import err_pb2 as err__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11masteradmin.proto\x12\x10gsdk.masteradmin\x1a\nuser.proto\x1a\terr.proto\"\x1e\n\nGetRequest\x12\x10\n\x08\x64\x65viceID\x18\x01 \x01(\r\"7\n\x0bGetResponse\x12(\n\x0bmasterAdmin\x18\x01 \x01(\x0b\x32\x13.gsdk.user.UserInfo\"H\n\nSetRequest\x12\x10\n\x08\x64\x65viceID\x18\x01 \x01(\r\x12(\n\x0bmasterAdmin\x18\x02 \x01(\x0b\x32\x13.gsdk.user.UserInfo\"\r\n\x0bSetResponse\"N\n\x0fSetMultiRequest\x12\x11\n\tdeviceIDs\x18\x01 \x03(\r\x12(\n\x0bmasterAdmin\x18\x02 \x01(\x0b\x32\x13.gsdk.user.UserInfo\"A\n\x10SetMultiResponse\x12-\n\x0c\x64\x65viceErrors\x18\x01 \x03(\x0b\x32\x17.gsdk.err.ErrorResponse*N\n\x04\x45num\x12!\n\x1d\x46IRST_ENUM_VALUE_MUST_BE_ZERO\x10\x00\x12#\n\x1fMAX_NUM_OF_CARD_PER_MASTERADMIN\x10\x04\x32\xe8\x01\n\x0bMasterAdmin\x12\x42\n\x03Get\x12\x1c.gsdk.masteradmin.GetRequest\x1a\x1d.gsdk.masteradmin.GetResponse\x12\x42\n\x03Set\x12\x1c.gsdk.masteradmin.SetRequest\x1a\x1d.gsdk.masteradmin.SetResponse\x12Q\n\x08SetMulti\x12!.gsdk.masteradmin.SetMultiRequest\x1a\".gsdk.masteradmin.SetMultiResponseB?\n\x1e\x63om.supremainc.sdk.masteradminP\x01Z\x1b\x62iostar/service/masteradminb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'masteradmin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.supremainc.sdk.masteradminP\001Z\033biostar/service/masteradmin'
  _globals['_ENUM']._serialized_start=387
  _globals['_ENUM']._serialized_end=465
  _globals['_GETREQUEST']._serialized_start=62
  _globals['_GETREQUEST']._serialized_end=92
  _globals['_GETRESPONSE']._serialized_start=94
  _globals['_GETRESPONSE']._serialized_end=149
  _globals['_SETREQUEST']._serialized_start=151
  _globals['_SETREQUEST']._serialized_end=223
  _globals['_SETRESPONSE']._serialized_start=225
  _globals['_SETRESPONSE']._serialized_end=238
  _globals['_SETMULTIREQUEST']._serialized_start=240
  _globals['_SETMULTIREQUEST']._serialized_end=318
  _globals['_SETMULTIRESPONSE']._serialized_start=320
  _globals['_SETMULTIRESPONSE']._serialized_end=385
  _globals['_MASTERADMIN']._serialized_start=468
  _globals['_MASTERADMIN']._serialized_end=700
# @@protoc_insertion_point(module_scope)
